name: CI/CD AWS LifeCycle

on:
  push:
    paths:
      - '**'
      - '.github/workflows/s3_lifecycle_delta.yml'
    branches: [main]

jobs:
  build-test-upload:
    name: AWS LifeCycle
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and req
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: Run unit tests
        run: |
          pytest tests/

